#!/bin/sh

getent group greetd || /usr/sbin/groupadd -r greetd
getent passwd greetd || /usr/sbin/useradd -r -g greetd -G video,tty -d /run/greetd -c "Greetd User" -s /sbin/nologin greetd
/usr/bin/passwd -l greetd
