#!/bin/sh

if [ -x /usr/bin/gtk-update-icon-cache ]; then
	gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
fi

if [ -x /usr/bin/update-desktop-database ]; then
	update-desktop-database -q /usr/share/applications
fi
